### ISSUE TITLE
Save to Worklist button

### ISSUE THREAD

**Issue by rlnsy** [chenvictor/CourseScheduler#1]
Just wondering if this is supposed to work, or if it's under development still? Am logged in to CWL but can't seem to save worklists.

**Comment by chenvictor** [comment]
It should prompt a login (if not already logged in), then prompt a Worklist name to save under.
Then a confirmation pop-up should display after a moment.

![step_1](https://user-images.githubusercontent.com/32944695/42185320-4b6bc640-7dfd-11e8-991b-2d8dbdd044c4.PNG)
![step_2](https://user-images.githubusercontent.com/32944695/42185321-4b820cfc-7dfd-11e8-991e-286a44734eb6.PNG)
![step_3](https://user-images.githubusercontent.com/32944695/42185322-4b9b79c6-7dfd-11e8-8686-4e993d218222.PNG)
